# Generated by Django 5.2.7 on 2025-10-05 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0002_device_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='api_key',
        ),
    ]
