# Generated by Django 5.2.7 on 2025-10-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0003_remove_device_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='api_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
